package plugin

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	dynfake "k8s.io/client-go/dynamic/fake"
	k8sfake "k8s.io/client-go/kubernetes/fake"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	k8stesting "k8s.io/client-go/testing"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	"github.com/capybara/capybara/api/v1alpha1"
	"github.com/capybara/capybara/pkg/audit"
	"github.com/capybara/capybara/pkg/auth"
)

const argoDir = "../../plugins/argocd"

var appGVR = schema.GroupVersionResource{Group: "argoproj.io", Version: "v1alpha1", Resource: "applications"}

func argoSpec(t *testing.T) *v1alpha1.PluginSpec {
	t.Helper()
	_, spec, err := LoadDir(argoDir, "builtin")
	if err != nil {
		t.Fatal(err)
	}
	return spec
}

func renderArgo(t *testing.T, spec *v1alpha1.PluginSpec, cfg map[string]any) []*unstructured.Unstructured {
	t.Helper()
	ch, values, err := LoadInstallChart(argoDir, spec, "dev-1", cfg)
	if err != nil {
		t.Fatal(err)
	}
	r, err := Render(context.Background(), ch, RenderOptions{ReleaseName: spec.Chart.ReleaseName, Namespace: spec.Chart.Namespace, Values: values, KubeVersion: "v1.35.5"})
	if err != nil {
		t.Fatal(err)
	}
	return r.Objects
}

// The chart with Capybara's preset: only what the manifest declares, CRDs
// kept on uninstall, no API server, Dex, notifications or running
// ApplicationSet controller, every container "restricted", and the proxy
// settings reaching the repo server.
func TestArgoCDChart(t *testing.T) {
	spec := argoSpec(t)
	objs := renderArgo(t, spec, map[string]any{"httpsProxy": "http://proxy.corp:3128", "noProxy": ".svc,.cluster.local"})
	rules, nsRules := InstallerRules(spec, v1alpha1.ModeInstall, nil, spec.Chart.Namespace)
	rules = append(rules, nsRules...)
	var crds, deployments []string
	for _, o := range objs {
		gvr := guessResource(o)
		for _, verb := range []string{"create", "delete"} {
			if !allows(rules, gvr.Group, gvr.Resource, verb) {
				t.Errorf("%s %s %s: not declared", verb, o.GetKind(), o.GetName())
			}
		}
		switch o.GetKind() {
		case "CustomResourceDefinition":
			crds = append(crds, o.GetName())
			if o.GetAnnotations()[HelmResourcePolicy] != "keep" {
				t.Errorf("CRD %s is not kept on uninstall", o.GetName())
			}
		case "Deployment", "StatefulSet":
			replicas, _, _ := unstructured.NestedFieldNoCopy(o.Object, "spec", "replicas")
			deployments = append(deployments, fmt.Sprintf("%s=%v", o.GetName(), replicas))
			pod, _, _ := unstructured.NestedMap(o.Object, "spec", "template", "spec")
			if nonRoot, _, _ := unstructured.NestedBool(pod, "securityContext", "runAsNonRoot"); !nonRoot {
				t.Errorf("%s: pod not runAsNonRoot", o.GetName())
			}
			if sp, _, _ := unstructured.NestedString(pod, "securityContext", "seccompProfile", "type"); sp != "RuntimeDefault" {
				t.Errorf("%s: seccomp %q", o.GetName(), sp)
			}
			containers, _, _ := unstructured.NestedSlice(pod, "containers")
			inits, _, _ := unstructured.NestedSlice(pod, "initContainers")
			for _, c := range append(containers, inits...) {
				cm := c.(map[string]any)
				esc, found, _ := unstructured.NestedBool(cm, "securityContext", "allowPrivilegeEscalation")
				drop, _, _ := unstructured.NestedStringSlice(cm, "securityContext", "capabilities", "drop")
				if !found || esc || !slices.Contains(drop, "ALL") {
					t.Errorf("%s/%s: not restricted (escalation %v, drop %v)", o.GetName(), cm["name"], esc, drop)
				}
				if cm["name"] == "repo-server" {
					env, _ := json.Marshal(cm["env"])
					if !strings.Contains(string(env), `{"name":"HTTPS_PROXY","value":"http://proxy.corp:3128"}`) || !strings.Contains(string(env), `"value":".svc,.cluster.local"`) {
						t.Errorf("repo server env = %s", env)
					}
				}
			}
			if vols, _, _ := unstructured.NestedSlice(pod, "volumes"); strings.Contains(fmt.Sprint(vols), "hostPath") {
				t.Errorf("%s: hostPath volume", o.GetName())
			}
		case "Job":
			t.Errorf("unexpected Job %s (Redis's password is generated by Capybara)", o.GetName())
		}
		if strings.Contains(o.GetName(), "server") && o.GetKind() == "Deployment" && o.GetName() != "argocd-repo-server" {
			t.Errorf("unexpected %s %s", o.GetKind(), o.GetName())
		}
		if strings.Contains(o.GetName(), "dex") || strings.Contains(o.GetName(), "notifications") {
			t.Errorf("unexpected %s %s", o.GetKind(), o.GetName())
		}
	}
	slices.Sort(crds)
	if fmt.Sprint(crds) != "[applications.argoproj.io applicationsets.argoproj.io appprojects.argoproj.io]" {
		t.Errorf("CRDs = %v", crds)
	}
	slices.Sort(deployments)
	if fmt.Sprint(deployments) != "[argocd-application-controller=1 argocd-applicationset-controller=0 argocd-redis=1 argocd-repo-server=1]" {
		t.Errorf("workloads = %v", deployments)
	}
}

// The default AppProject is locked (a chart hook): no sources, destinations
// or kinds, and no Applications from any other namespace.
func TestArgoCDDefaultProjectIsLocked(t *testing.T) {
	spec := argoSpec(t)
	var found bool
	for _, o := range renderArgo(t, spec, nil) {
		if o.GetKind() != "AppProject" {
			continue
		}
		if o.GetName() != "default" || o.GetNamespace() != "argocd" {
			t.Errorf("unexpected AppProject %s/%s", o.GetNamespace(), o.GetName())
		}
		found = true
		for _, f := range []string{"sourceRepos", "destinations", "sourceNamespaces", "clusterResourceWhitelist"} {
			if v, _, _ := unstructured.NestedSlice(o.Object, "spec", f); len(v) != 0 {
				t.Errorf("default.%s = %v", f, v)
			}
		}
		black, _, _ := unstructured.NestedSlice(o.Object, "spec", "namespaceResourceBlacklist")
		if fmt.Sprint(black) != "[map[group:* kind:*]]" {
			t.Errorf("default.namespaceResourceBlacklist = %v", black)
		}
		if !strings.Contains(o.GetAnnotations()["helm.sh/hook"], "post-upgrade") || o.GetLabels()[v1alpha1.LabelPlugin] != "argocd" {
			t.Errorf("default AppProject: annotations %v, labels %v", o.GetAnnotations(), o.GetLabels())
		}
	}
	if !found {
		t.Fatal("no default AppProject")
	}
}

// Each Project's generated AppProject: Applications only from its own
// namespace, into it, on this cluster; no cluster kinds; never quota,
// limits, network policies or role bindings.
func TestArgoCDProjectAppProject(t *testing.T) {
	spec := argoSpec(t)
	objs := spec.Permissions.Project.Objects
	if len(objs) != 1 || !objs[0].InPluginNamespace || objs[0].Resource != "appprojects" {
		t.Fatalf("project objects = %+v", objs)
	}
	o, err := RenderProjectObject(objs[0], ProjectRef{Name: "team-a", Namespace: "team-a-dev"}, "dev-1", "argocd")
	if err != nil {
		t.Fatal(err)
	}
	if o.GetName() != "capybara-team-a" || o.GetNamespace() != "argocd" {
		t.Errorf("AppProject %s/%s", o.GetNamespace(), o.GetName())
	}
	sources, _, _ := unstructured.NestedStringSlice(o.Object, "spec", "sourceNamespaces")
	dest, _, _ := unstructured.NestedSlice(o.Object, "spec", "destinations")
	white, found, _ := unstructured.NestedSlice(o.Object, "spec", "clusterResourceWhitelist")
	black, _, _ := unstructured.NestedSlice(o.Object, "spec", "namespaceResourceBlacklist")
	if fmt.Sprint(sources) != "[team-a-dev]" || fmt.Sprint(dest) != "[map[namespace:team-a-dev server:https://kubernetes.default.svc]]" || !found || len(white) != 0 {
		t.Errorf("sources %v, destinations %v, cluster kinds %v (%v)", sources, dest, white, found)
	}
	var kinds []string
	for _, b := range black {
		kinds = append(kinds, b.(map[string]any)["kind"].(string))
	}
	if fmt.Sprint(kinds) != "[ResourceQuota LimitRange NetworkPolicy RoleBinding]" {
		t.Errorf("refused kinds = %v", kinds)
	}
	// Installer: the AppProjects in Argo CD's namespace only, in connect mode.
	_, ns := InstallerRules(spec, v1alpha1.ModeConnect, nil, "openshift-gitops")
	if !allows(ns, "argoproj.io", "appprojects", "create") {
		t.Error("connect installer cannot create the generated AppProjects")
	}
}

// Capybara never holds a write permission on ApplicationSets.
func TestArgoCDNoApplicationSetWrites(t *testing.T) {
	spec := argoSpec(t)
	for name, rules := range map[string][]v1alpha1.PolicyRule{
		"console": spec.Permissions.Console.ClusterRules,
		"project": spec.Permissions.Project.Rules,
	} {
		for _, verb := range []string{"get", "create", "update", "patch", "delete"} {
			if allows(toRBAC(rules), "argoproj.io", "applicationsets", verb) {
				t.Errorf("%s grants %s on applicationsets", name, verb)
			}
		}
	}
	for _, mode := range []v1alpha1.InstallMode{v1alpha1.ModeInstall, v1alpha1.ModeConnect} {
		c, n := InstallerRules(spec, mode, nil, "argocd")
		for _, verb := range []string{"create", "update", "patch", "delete"} {
			if allows(append(c, n...), "argoproj.io", "applicationsets", verb) {
				t.Errorf("%s installer may %s applicationsets", mode, verb)
			}
		}
	}
}

type argoFixture struct {
	objectFixture
	in *v1alpha1.PluginInstallation
}

// newArgoAPI: GitOps installed on dev-1 (apps-in-any-namespace passed
// unless viewOnly), a Ready Project "team-a" with namespace "team-a-dev",
// and an Application "web" there.
func newArgoAPI(t *testing.T, viewOnly bool) *argoFixture {
	t.Helper()
	spec := argoSpec(t)
	p := &v1alpha1.Plugin{ObjectMeta: metav1.ObjectMeta{Name: "argocd"}, Spec: *spec, Status: v1alpha1.PluginStatus{Available: true}}
	step := v1alpha1.StepDone
	if viewOnly {
		step = v1alpha1.StepOff
	}
	in := &v1alpha1.PluginInstallation{ObjectMeta: metav1.ObjectMeta{Name: "argocd.dev-1"},
		Spec: v1alpha1.PluginInstallationSpec{Plugin: "argocd", Cluster: "dev-1", Mode: v1alpha1.ModeConnect, Enabled: true, Version: spec.Version},
		Status: v1alpha1.PluginInstallationStatus{Phase: v1alpha1.InstallReady, InstalledVersion: spec.Version,
			Steps: []v1alpha1.StepStatus{{Name: "api", State: v1alpha1.StepDone}, {Name: WriteStepForTest, State: step}}}}
	pr := &v1alpha1.Project{ObjectMeta: metav1.ObjectMeta{Name: "team-a"},
		Spec: v1alpha1.ProjectSpec{Cluster: "dev-1", Namespace: "team-a-dev", Owner: "devs", Size: "S"}, Status: v1alpha1.ProjectStatus{Phase: v1alpha1.PhaseReady}}
	scheme := runtime.NewScheme()
	_ = clientgoscheme.AddToScheme(scheme)
	_ = v1alpha1.AddToScheme(scheme)
	mgmt := fake.NewClientBuilder().WithScheme(scheme).WithObjects(p, in, pr).WithStatusSubresource(&v1alpha1.Project{}).Build()

	dyn := dynfake.NewSimpleDynamicClientWithCustomListKinds(runtime.NewScheme(), map[schema.GroupVersionResource]string{appGVR: "ApplicationList"},
		unstr(t, `{apiVersion: argoproj.io/v1alpha1, kind: Application, metadata: {name: web, namespace: team-a-dev, uid: a1, resourceVersion: "5", finalizers: [resources-finalizer.argocd.argoproj.io]},
spec: {project: capybara-team-a, source: {repoURL: "https://git.example/apps.git", path: web}, destination: {server: "https://kubernetes.default.svc", namespace: team-a-dev}},
status: {sync: {status: Synced}}}`))
	dyn.PrependReactor("create", "*", func(action k8stesting.Action) (bool, runtime.Object, error) {
		ca := action.(k8stesting.CreateActionImpl)
		o := ca.GetObject().(*unstructured.Unstructured)
		if len(ca.CreateOptions.DryRun) > 0 {
			return true, o, nil
		}
		if o.GetUID() == "" {
			o.SetUID(types.UID("uid-" + o.GetName()))
		}
		return false, nil, nil
	})
	dyn.PrependReactor("update", "*", func(action k8stesting.Action) (bool, runtime.Object, error) {
		ua := action.(k8stesting.UpdateActionImpl)
		if len(ua.UpdateOptions.DryRun) > 0 {
			return true, ua.GetObject(), nil
		}
		return false, nil, nil
	})
	cs := k8sfake.NewClientset()
	path := filepath.Join(t.TempDir(), "audit.jsonl")
	store, _ := audit.NewFileStore(path)
	auditor := audit.NewAuditor(store, quiet)
	objects := &ObjectAPI{Mgmt: mgmt, Clusters: fakeObjectClusters{dyn: dyn, cs: cs}, Auditor: auditor, Logger: quiet}
	actions := &ActionAPI{Mgmt: mgmt, Clusters: fakeDyn{dyn}, Auditor: auditor, Logger: quiet, Objects: objects}
	mux := http.NewServeMux()
	objects.Register(mux)
	actions.Register(mux)
	srv := httptest.NewServer(auth.Middleware(mux))
	t.Cleanup(srv.Close)
	return &argoFixture{objectFixture: objectFixture{apiFixture: apiFixture{srv: srv, c: mgmt, auditPath: path, store: store}, dyn: dyn, cs: cs}, in: in}
}

// WriteStepForTest is the step that unlocks writes (plugin.yaml).
const WriteStepForTest = "apps-in-any-namespace"

const appBase = "/api/clusters/dev-1/plugin-objects/argocd/applications/"

func TestArgoCDApplicationPolicy(t *testing.T) {
	f := newArgoAPI(t, false)
	ctx := context.Background()

	// The form sends only what the user chose: the Project's AppProject and
	// destination are filled in.
	code, body := f.do(t, http.MethodPost, appBase+"team-a-dev", ObjectRequest{Object: yamlObj(t, `
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: guestbook, finalizers: [resources-finalizer.argocd.argoproj.io]}
spec: {source: {repoURL: "https://github.com/argoproj/argocd-example-apps.git", path: guestbook, targetRevision: HEAD}}`)})
	if code != 200 {
		t.Fatalf("create: %d %v", code, body)
	}
	got, err := f.dyn.Resource(appGVR).Namespace("team-a-dev").Get(ctx, "guestbook", metav1.GetOptions{})
	if err != nil {
		t.Fatal(err)
	}
	project, _, _ := unstructured.NestedString(got.Object, "spec", "project")
	dest, _, _ := unstructured.NestedStringMap(got.Object, "spec", "destination")
	if project != "capybara-team-a" || dest["namespace"] != "team-a-dev" || dest["server"] != "https://kubernetes.default.svc" {
		t.Errorf("defaults: project %q, destination %v", project, dest)
	}

	refused := func(y, want string) {
		t.Helper()
		code, body := f.do(t, http.MethodPost, appBase+"team-a-dev/_validate", ObjectRequest{Object: yamlObj(t, y)})
		if code != 200 || problemPaths(body) != want {
			t.Errorf("%s\n  got %d %s %v\n  want %s", y, code, problemPaths(body), body["problems"], want)
		}
	}
	src := `source: {repoURL: "https://git.example/x"}`
	refused(`{metadata: {name: a}, spec: {project: default, `+src+`}}`, "spec.project")
	refused(`{metadata: {name: a}, spec: {project: capybara-team-b, `+src+`}}`, "spec.project")
	refused(`{metadata: {name: a}, spec: {destination: {namespace: kube-system}, `+src+`}}`, "spec.destination.namespace")
	refused(`{metadata: {name: a}, spec: {destination: {server: "https://other:6443"}, `+src+`}}`, "spec.destination.server")
	refused(`{metadata: {name: a}, spec: {destination: {name: in-cluster}, `+src+`}}`, "spec.destination.name")
	refused(`{metadata: {name: a}, spec: {source: {repoURL: "git@github.com:x/y.git"}}}`, "spec.source.repoURL")
	refused(`{metadata: {name: a}, spec: {source: {repoURL: "http://example.com/x.git"}}}`, "spec.source.repoURL")
	refused(`{metadata: {name: a}, spec: {source: {repoURL: "ssh://git@github.com/x"}}}`, "spec.source.repoURL")
	refused(`{metadata: {name: a}, spec: {sources: [{repoURL: "https://x"}]}}`, "spec.sources")
	refused(`{metadata: {name: a}, spec: {source: {repoURL: "https://x", plugin: {name: p}}}}`, "spec.source.plugin")
	refused(`{metadata: {name: a}, spec: {`+src+`, syncPolicy: {syncOptions: [CreateNamespace=true]}}}`, "spec.syncPolicy.syncOptions[0]")
	refused(`{metadata: {name: a}, spec: {`+src+`, syncPolicy: {managedNamespaceMetadata: {labels: {a: b}}}}}`, "spec.syncPolicy.managedNamespaceMetadata")
	refused(`{metadata: {name: a, finalizers: [example.com/x]}, spec: {`+src+`}}`, "metadata.finalizers[0]")
	refused(`{metadata: {name: a}, spec: {`+src+`}, operation: {sync: {}}}`, "operation")
	// In-cluster http:// and git:// are fine.
	refused(`{metadata: {name: a}, spec: {source: {repoURL: "git://git.e2e-git.svc.cluster.local/repo"}}}`, "")
	refused(`{metadata: {name: a}, spec: {source: {repoURL: "http://gitea.tools.svc:3000/x/y.git"}}}`, "")

	// The message names the Project's own AppProject.
	_, body = f.do(t, http.MethodPost, appBase+"team-a-dev/_validate", ObjectRequest{Object: yamlObj(t, `{metadata: {name: a}, spec: {project: default, `+src+`}}`)})
	if !strings.Contains(fmt.Sprint(body["problems"]), "capybara-team-a") {
		t.Errorf("message = %v", body["problems"])
	}

	// Outside a Project namespace: refused before the policy.
	if code, _ := f.do(t, http.MethodPost, appBase+"argocd", ObjectRequest{Object: yamlObj(t, `{metadata: {name: a}, spec: {`+src+`}}`)}); code != http.StatusForbidden {
		t.Errorf("create in argocd: %d", code)
	}
}

func TestArgoCDDeleteModes(t *testing.T) {
	f := newArgoAPI(t, false)
	ctx := context.Background()
	if code, body := f.do(t, http.MethodDelete, appBase+"team-a-dev/web?uid=a1", nil); code != http.StatusBadRequest || !strings.Contains(fmt.Sprint(body["error"]), "cascade or app-only") {
		t.Errorf("delete without a mode: %d %v", code, body)
	}
	// App only: the finalizer goes first (the fake keeps the object, as a
	// cluster would while finalizers remain).
	var patches []string
	f.dyn.PrependReactor("patch", "applications", func(action k8stesting.Action) (bool, runtime.Object, error) {
		patches = append(patches, string(action.(k8stesting.PatchAction).GetPatch()))
		return false, nil, nil
	})
	if code, body := f.do(t, http.MethodDelete, appBase+"team-a-dev/web?uid=a1&mode=app-only", nil); code != 200 {
		t.Fatalf("delete app only: %d %v", code, body)
	}
	if len(patches) != 1 || patches[0] != `{"metadata":{"finalizers":[],"resourceVersion":"5"}}` {
		t.Errorf("patches = %v", patches)
	}
	if _, err := f.dyn.Resource(appGVR).Namespace("team-a-dev").Get(ctx, "web", metav1.GetOptions{}); err == nil {
		t.Error("not deleted")
	}
	recs, _ := f.store.List(ctx, audit.Filter{})
	if len(recs) == 0 || recs[0].Action != "argocd.delete" || !strings.Contains(recs[0].Detail, "Application only") {
		t.Errorf("audit = %+v", recs)
	}
}

func TestArgoCDCascadeDeleteEnsuresFinalizer(t *testing.T) {
	f := newArgoAPI(t, false)
	ctx := context.Background()
	app, _ := f.dyn.Resource(appGVR).Namespace("team-a-dev").Get(ctx, "web", metav1.GetOptions{})
	app.SetFinalizers(nil)
	_, _ = f.dyn.Resource(appGVR).Namespace("team-a-dev").Update(ctx, app, metav1.UpdateOptions{})
	var patches []string
	f.dyn.PrependReactor("patch", "applications", func(action k8stesting.Action) (bool, runtime.Object, error) {
		patches = append(patches, string(action.(k8stesting.PatchAction).GetPatch()))
		return false, nil, nil
	})
	if code, body := f.do(t, http.MethodDelete, appBase+"team-a-dev/web?uid=a1&mode=cascade", nil); code != 200 {
		t.Fatalf("cascade delete: %d %v", code, body)
	}
	if len(patches) != 1 || !strings.Contains(patches[0], `"finalizers":["resources-finalizer.argocd.argoproj.io"]`) {
		t.Errorf("patches = %v", patches)
	}
}

// Connected to an Argo CD that only watches its own namespace: nothing is
// written (objects or actions), reading still works.
func TestArgoCDViewOnly(t *testing.T) {
	f := newArgoAPI(t, true)
	if code, body := f.do(t, http.MethodPost, appBase+"team-a-dev", ObjectRequest{Object: yamlObj(t, `{metadata: {name: a}, spec: {source: {repoURL: "https://x"}}}`)}); code != http.StatusForbidden || !strings.Contains(fmt.Sprint(body["error"]), "view-only") {
		t.Errorf("create: %d %v", code, body)
	}
	if code, _ := f.do(t, http.MethodDelete, appBase+"team-a-dev/web?uid=a1&mode=cascade", nil); code != http.StatusForbidden {
		t.Errorf("delete: %d", code)
	}
	if code, body := f.do(t, http.MethodPost, "/api/clusters/dev-1/plugin-actions/argocd/refresh", ActionRequest{Namespace: "team-a-dev", Name: "web", UID: "a1"}); code != http.StatusForbidden {
		t.Errorf("refresh: %d %v", code, body)
	}
}

func TestArgoCDActions(t *testing.T) {
	f := newArgoAPI(t, false)
	ctx := context.Background()
	act := func(name string, req ActionRequest) (int, map[string]any) {
		req.Namespace, req.Name, req.UID = "team-a-dev", "web", "a1"
		return f.do(t, http.MethodPost, "/api/clusters/dev-1/plugin-actions/argocd/"+name, req)
	}
	get := func() *unstructured.Unstructured {
		o, _ := f.dyn.Resource(appGVR).Namespace("team-a-dev").Get(ctx, "web", metav1.GetOptions{})
		return o
	}

	if code, body := act("refresh", ActionRequest{}); code != 200 || get().GetAnnotations()["argocd.argoproj.io/refresh"] != "normal" {
		t.Errorf("refresh: %d %v", code, body)
	}
	// Prune asks for the name; the operation records the user.
	if code, body := act("sync", ActionRequest{Inputs: map[string]any{"prune": true}}); code != http.StatusBadRequest || !strings.Contains(fmt.Sprint(body["error"]), "type the name web") {
		t.Errorf("prune without the name: %d %v", code, body)
	}
	if code, body := act("sync", ActionRequest{Inputs: map[string]any{"prune": true, "revision": "v2"}, ConfirmName: "web"}); code != 200 {
		t.Fatalf("sync: %d %v", code, body)
	}
	op, _, _ := unstructured.NestedMap(get().Object, "operation")
	if fmt.Sprint(op) != "map[initiatedBy:map[username:dev] sync:map[prune:true revision:v2]]" {
		t.Errorf("operation = %v", op)
	}
	// While it runs, no second sync or rollback.
	if code, body := act("sync", ActionRequest{Inputs: map[string]any{"prune": false}}); code != http.StatusConflict || !strings.Contains(fmt.Sprint(body["error"]), "operation is set") {
		t.Errorf("sync during a sync: %d %v", code, body)
	}
	app := get()
	unstructured.RemoveNestedField(app.Object, "operation")
	_, _ = f.dyn.Resource(appGVR).Namespace("team-a-dev").Update(ctx, app, metav1.UpdateOptions{})

	// Without the operation field: a sync without a revision leaves it out.
	if code, _ := act("sync", ActionRequest{Inputs: map[string]any{"prune": false}}); code != 200 {
		t.Fatal("plain sync refused")
	}
	if rev, found, _ := unstructured.NestedFieldNoCopy(get().Object, "operation", "sync", "revision"); found {
		t.Errorf("revision = %v", rev)
	}
	app = get()
	unstructured.RemoveNestedField(app.Object, "operation")
	_, _ = f.dyn.Resource(appGVR).Namespace("team-a-dev").Update(ctx, app, metav1.UpdateOptions{})

	// Sync policy: self-heal needs auto-sync; auto-prune asks for the name.
	if code, _ := act("self-heal-on", ActionRequest{}); code != http.StatusConflict {
		t.Errorf("self-heal without auto-sync: %d", code)
	}
	if code, body := act("auto-sync-on", ActionRequest{}); code != 200 {
		t.Fatalf("auto-sync on: %d %v", code, body)
	}
	if code, _ := act("auto-sync-on", ActionRequest{}); code != http.StatusConflict {
		t.Errorf("auto-sync on twice: %d", code)
	}
	if code, _ := act("auto-prune-on", ActionRequest{}); code != http.StatusBadRequest {
		t.Errorf("auto-prune without the name: %d", code)
	}
	if code, _ := act("auto-prune-on", ActionRequest{ConfirmName: "web"}); code != 200 {
		t.Error("auto-prune on refused")
	}
	if code, _ := act("self-heal-on", ActionRequest{}); code != 200 {
		t.Error("self-heal on refused")
	}
	automated, _, _ := unstructured.NestedMap(get().Object, "spec", "syncPolicy", "automated")
	if fmt.Sprint(automated) != "map[prune:true selfHeal:true]" {
		t.Errorf("automated = %v", automated)
	}
	// Rollback is refused while auto-sync is on (it would sync back).
	if code, body := act("sync-revision", ActionRequest{Inputs: map[string]any{"revision": "abc123"}}); code != http.StatusConflict || !strings.Contains(fmt.Sprint(body["error"]), "spec.syncPolicy.automated is set") {
		t.Errorf("rollback with auto-sync: %d %v", code, body)
	}
	if code, _ := act("auto-sync-off", ActionRequest{}); code != 200 {
		t.Fatal("auto-sync off refused")
	}
	if _, found, _ := unstructured.NestedFieldNoCopy(get().Object, "spec", "syncPolicy", "automated"); found {
		t.Error("automated kept after auto-sync off")
	}
	if code, body := act("sync-revision", ActionRequest{Inputs: map[string]any{"revision": "abc123"}}); code != 200 {
		t.Errorf("rollback: %d %v", code, body)
	}
	if rev, _, _ := unstructured.NestedString(get().Object, "operation", "sync", "revision"); rev != "abc123" {
		t.Errorf("rollback revision = %q", rev)
	}
	// Audited as argocd.<action>.
	recs, _ := f.store.List(ctx, audit.Filter{})
	var names []string
	for _, r := range recs {
		names = append(names, r.Action+"="+string(r.Result))
	}
	if !slices.Contains(names, "argocd.sync-revision=success") || !slices.Contains(names, "argocd.auto-prune-on=failure") {
		t.Errorf("audit = %v", names)
	}
}
